services:
  local:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "25565:25565"
    volumes:
      - ./services/server/data:/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 22G
        reservations:
          memory: 16G
