services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
      args:
        MEMORY_MIN: 4G
        MEMORY_MAX: 16G
        EULA: "true"
        OPS: top_tier_couch
    ports:
      - "25565:25565"
    volumes:
      - minecraft:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  minecraft:
