services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    environment:
      EULA: true
      MEMORY_MIN: 8G
      MEMORY_MAX: 16G
      MOTD: "Who's the best boss?"
      DIFFICULTY: "normal"
      MAX_PLAYERS: 10
      VIEW_DISTANCE: 32
      ENABLE_RCON: true
      RCON_PASSWORD: "password"
    ports:
      - "25565:25565"
    volumes:
      - minecraft:/data
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 20G
volumes:
  minecraft:
