services:
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    environment:
      EULA: true
      MEMORY_MIN: 20G
      MEMORY_MAX: 32G
      EXIT_ON_OOM: true
      MOTD: "Who's the best boss?"
      DIFFICULTY: "normal"
      MAX_PLAYERS: 10
      VIEW_DISTANCE: 32
    ports:
      - "25565:25565"
    volumes:
      - minecraft:/data
    stdin_open: true
    tty: true
volumes:
  minecraft:
